<?php

namespace WC\BaseBundle\Repository;

/**
 * RecoveryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecoveryRepository extends \Doctrine\ORM\EntityRepository
{
}
