<?php

namespace WC\GuildBundle\Repository;

/**
 * CharactersBlackGuildRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CharactersBlackGuildRepository extends \Doctrine\ORM\EntityRepository
{
}
