<?php

namespace WC\GuildBundle\Repository;

/**
 * CharactersPuGuildRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CharactersPuGuildRepository extends \Doctrine\ORM\EntityRepository
{
}
